### ISSUE TITLE
print left right format not symmetrical

### ISSUE THREAD

**Issue by zainnardo** [andresperezmelo/print_bluetooth_termal#2]
i try to print with left right option, then im use column for that but when i try to use 2 column at the same time its not symmetric between left and right, at the left side the printed font just little bit into right and looks like new paragraph

**Comment by andresperezmelo** [comment]
I would like you to provide a photo or capture, to see the case well.

Note that the library [esc_pos_utils_plus](https://pub.dev/packages/esc_pos_utils_plus) has a way of printing in a table, the table has a width of 12 points, which must be managed when creating the table so that it is organized.

```dart
generator.row([
    PosColumn(
      text: 'col3',
      width: 3,
      styles: PosStyles(align: PosAlign.center, underline: true),
    ),
    PosColumn(
      text: 'col6',
      width: 6,
      styles: PosStyles(align: PosAlign.center, underline: true),
    ),
    PosColumn(
      text: 'col3',
      width: 3,
      styles: PosStyles(align: PosAlign.center, underline: true),
    ),
  ]);
```
