### ISSUE TITLE
Print not in center

### ISSUE THREAD

**Issue by ferns-it** [andresperezmelo/print_bluetooth_termal#7]
I tested the example package, it is working properly. But when I used in my real project. The text is not print in center. I already changed the "Pos Align: Center". But still not working

**Comment by andresperezmelo** [comment]
**You need to add the PostAlign.center**

tested version: **esc_pos_utils_plus: ^2.0.1+6**

### a simple example

```dart
CapabilityProfile profile = await CapabilityProfile.load();
    final generator = Generator(PaperSize.mm58, profile);
    List<int> bytes = [];
    bytes += generator.setGlobalFont(PosFontType.fontA);

bytes += generator.text("Bussines", styles: PosStyles(align: PosAlign.center));
```
_try the example and tell me_

**Comment by andresperezmelo** [comment]
You can use the same example but use

Letf
```dart
bytes += generator.text("Bussines", styles: PosStyles(align: PosAlign.letf));
```

rigth
```dart
bytes += generator.text("Bussines", styles: PosStyles(align: PosAlign.rigth));
```

You can also use tables, the table must be divided into 12 spaces, each PostColumn -> width

bytes += generator.row([
      PosColumn(
        text: 'Name:',
        width: 8,
        styles: PosStyles(
          align: PosAlign.left,
        ),
      ),
      PosColumn(
        text: "Smits",
        width: 4,
        styles: PosStyles(
          align: PosAlign.left,
        ),
      ),
    ]);

**Comment by ferns-it** [comment]
I already tried this, but it doesn't work. The printer still print on center itself.

**Comment by andresperezmelo** [comment]
Try using the last example to use it to align the text

```dart
bytes += generator.row([
      PosColumn(
        text: 'Name:',
        width: 8,
        styles: PosStyles(
          align: PosAlign.left,
        ),
      ),
      PosColumn(
        text: "Smits",
        width: 4,
        styles: PosStyles(
          align: PosAlign.left,
        ),
      ),
    ]);
```
