### ISSUE TITLE
Doesnt print , please help

### ISSUE THREAD

**Issue by YahalomsGuy** [andresperezmelo/print_bluetooth_termal#8]
Hi, trying to print to Xprinter 365B (Bluetooth) with the below function , just not printing.

The app seems to be working perfectly.

The printer is working with Bluetooth, I have managed to print with native apps (both Android and IOS) downloaded from stores.
It is discovered in the devices list in the to of the app, connecting (I get a double beep on the printer when connecting) but absolutely nothing happens, not with the below function nor with the clean text function as appears in the example of this repository.

Is there a way to configure the printing method (like TSC mode)?  In one of the native apps I downloaded (android) there was an option to select "Printing method", it had 3 methods: receipts, TSC, TCPL, my printer is working only when selecting the TSC mode.

Any help will be greatly appreciated.

`Future<void> printTest() async {
    
bool connectionStatus = await PrintBluetoothThermal.connectionStatus;

    if (connectionStatus) {

      print(await PrintBluetoothThermal.disconnect);

      bool didConnect = await PrintBluetoothThermal.connect(

          macPrinterAddress: "DC:0D:30:18:42:6B");

      print(didConnect);

      print(await PrintBluetoothThermal.pairedBluetooths);

      print(await PrintBluetoothThermal.isPermissionBluetoothGranted);

      String enter = '\n';

      await PrintBluetoothThermal.writeBytes(enter.codeUnits);

      //size of 1-5

      String text = "Hello $enter";

      await PrintBluetoothThermal.writeString(

          printText: PrintTextSize(size: 1, text: "$text size 1"));

      await PrintBluetoothThermal.writeString(

          printText: PrintTextSize(size: 2, text: "$text size 2"));

      await PrintBluetoothThermal.writeString(

          printText: PrintTextSize(size: 3, text: "$text size 3"));

      await PrintBluetoothThermal.writeString(

          printText: PrintTextSize(size: 2, text: "$text size 4"));

      await PrintBluetoothThermal.writeString(

          printText: PrintTextSize(size: 3, text: "$text size 5"));

    } else {

      //not connected, reconnect

      print("the printer is disconnected ($connectionStatus)");

    }

  }`

**Comment by andresperezmelo** [comment]
The package works fine with generic printers, it doesn't work with some well-known brands, like Zebra, generally all generic brands work.

I am not very familiar with this type of TSC, TCPL printers, I do not know if it is specific printing codes or types of printers.

Does the printer have an sdk or cd of sample code?

**Comment by ozhankucuk** [comment]
> > The package works fine with generic printers, it doesn't work with some well-known brands, like Zebra, generally all generic brands work.
> > I am not very familiar with this type of TSC, TCPL printers, I do not know if it is specific printing codes or types of printers.
> > Does the printer have an sdk or cd of sample code?
> 
> Thank you for your response.
> 
> After a long struggle with all the packages in Pub.dev based on the MethodChannel, I figured out my printer will not work with them, It requires commands in a very specific format (the Tspl language) I have built it from scratch, based on Flutter_blue, and communicating directly with the Bluetooth Characteristic, working nice.
> 
> the upside, once done, it will probably work with every possible bluetooth printer, including those with ZPL (like zebra) Time will tell…..

hi, I need TSC printer integration.How can I do.Is there any sample on net.
Thanks

**Comment by bansalgaurav852** [comment]
> > The package works fine with generic printers, it doesn't work with some well-known brands, like Zebra, generally all generic brands work.
> > I am not very familiar with this type of TSC, TCPL printers, I do not know if it is specific printing codes or types of printers.
> > Does the printer have an sdk or cd of sample code?
> 
> Thank you for your response.
> 
> After a long struggle with all the packages in Pub.dev based on the MethodChannel, I figured out my printer will not work with them, It requires commands in a very specific format (the Tspl language) I have built it from scratch, based on Flutter_blue, and communicating directly with the Bluetooth Characteristic, working nice.
> 
> the upside, once done, it will probably work with every possible bluetooth printer, including those with ZPL (like zebra) Time will tell…..

hello can share your code i have to connect it with tsc printer

**Comment by bansalgaurav852** [comment]
thank you i will test it

**Comment by bansalgaurav852** [comment]
> > > > The package works fine with generic printers, it doesn't work with some well-known brands, like Zebra, generally all generic brands work.
> > > > I am not very familiar with this type of TSC, TCPL printers, I do not know if it is specific printing codes or types of printers.
> > > > Does the printer have an sdk or cd of sample code?
> > > 
> > > 
> > > Thank you for your response.
> > > After a long struggle with all the packages in Pub.dev based on the MethodChannel, I figured out my printer will not work with them, It requires commands in a very specific format (the Tspl language) I have built it from scratch, based on Flutter_blue, and communicating directly with the Bluetooth Characteristic, working nice.
> > > the upside, once done, it will probably work with every possible bluetooth printer, including those with ZPL (like zebra) Time will tell…..
> > 
> > 
> > hello can share your code i have to connect it with tsc printer
> 
> Hi, you can design with below link http://labelary.com/viewer.html
> 
> I used an other library .It works fine (only android) wise_bluetooth_print

it's not showing bluetooth device list in android 9 ,11 but showing in android 7
any way to make it work on new os version

**Comment by ozhankucuk** [comment]
> > > > > The package works fine with generic printers, it doesn't work with some well-known brands, like Zebra, generally all generic brands work.
> > > > > I am not very familiar with this type of TSC, TCPL printers, I do not know if it is specific printing codes or types of printers.
> > > > > Does the printer have an sdk or cd of sample code?
> > > > 
> > > > 
> > > > Thank you for your response.
> > > > After a long struggle with all the packages in Pub.dev based on the MethodChannel, I figured out my printer will not work with them, It requires commands in a very specific format (the Tspl language) I have built it from scratch, based on Flutter_blue, and communicating directly with the Bluetooth Characteristic, working nice.
> > > > the upside, once done, it will probably work with every possible bluetooth printer, including those with ZPL (like zebra) Time will tell…..
> > > 
> > > 
> > > hello can share your code i have to connect it with tsc printer
> > 
> > 
> > Hi, you can design with below link http://labelary.com/viewer.html
> > I used an other library .It works fine (only android) wise_bluetooth_print
> 
> it's not showing bluetooth device list in android 9 ,11 but showing in android 7 any way to make it work on new os version

we can use android 13. no problem.

**Comment by bansalgaurav852** [comment]
it's not printing anything
